# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
  push:
    branches: [ "2021.1" ]
  pull_request:
    branches: [ "2021.1" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Generate mcreator.gradle
      run: |
        cat > forge-1.12.2/workspacebase/mcreator.gradle << EOF
        EOF
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: zulu
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    - name: Project Testing
      run: |
        cd forge-1.12.2/workspacebase
        cat mcreator.gradle
        chmod +x gradlew
        ./gradlew tasks
        ./gradlew build